name: Comprobar compilación y ejecución de JavaScript
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v2
      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Instalar dependencias
        working-directory: ./src
        run: npm install
      - name: Ejecutar main.js
        working-directory: ./src/server
        run: node main.js &
      - name: Esperar 3 segundos
        run: sleep 3
      - name: Comprobar si se ejecutó correctamente
        run: curl -s -o /dev/null -w "%{http_code}" http://localhost:8080
        id: curl
      - name: Detener main.js
        run: pkill -f "node main.js"
      - name: Comprobar estado
        run: |
          if [ ${{ steps.curl.outputs.stdout }} -ne 200 ]; then
            echo "Error: el servidor no se ha iniciado correctamente."
            exit 1
          else
            echo "El servidor se ha iniciado correctamente."
          fi
