name: Comprobar compilación de JavaScript
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v2
      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Instalar dependencias
        working-directory: ./src
        run: npm install
      - name: Ejecutar main.js
        working-directory: ./src/server
        run: node main.js &
      - name: Esperar 5 segundos
        run: sleep 5
      - name: Detener main.js
        run: pkill -f "node main.js"
